/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulator;

/**
 *
 * @author LEGION
 */
public class Main_Kalkulator extends javax.swing.JFrame {
    String angka;
    double jumlah;
    double angka1;
    double angka2;
    int pilih;
    
    public Main_Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jT_result = new javax.swing.JTextField();
        jB_Clear = new javax.swing.JButton();
        jB_bagi = new javax.swing.JButton();
        jB_kali = new javax.swing.JButton();
        jB_kurang = new javax.swing.JButton();
        jB_tambah = new javax.swing.JButton();
        jB_samadengan = new javax.swing.JButton();
        jB_1 = new javax.swing.JButton();
        jB_2 = new javax.swing.JButton();
        jB_3 = new javax.swing.JButton();
        jB_4 = new javax.swing.JButton();
        jB_5 = new javax.swing.JButton();
        jB_6 = new javax.swing.JButton();
        jB_7 = new javax.swing.JButton();
        jB_8 = new javax.swing.JButton();
        jB_9 = new javax.swing.JButton();
        jB_0 = new javax.swing.JButton();
        jB_koma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator Sederhana");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jT_result.setEditable(false);
        jT_result.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_resultActionPerformed(evt);
            }
        });
        getContentPane().add(jT_result, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 60));

        jB_Clear.setText("C");
        jB_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ClearActionPerformed(evt);
            }
        });
        getContentPane().add(jB_Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 310, 60));

        jB_bagi.setText("/");
        jB_bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_bagiActionPerformed(evt);
            }
        });
        getContentPane().add(jB_bagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 100, 60));

        jB_kali.setText("X");
        jB_kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_kaliActionPerformed(evt);
            }
        });
        getContentPane().add(jB_kali, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 100, 60));

        jB_kurang.setText("-");
        jB_kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_kurangActionPerformed(evt);
            }
        });
        getContentPane().add(jB_kurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 100, 60));

        jB_tambah.setText("+");
        jB_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_tambahActionPerformed(evt);
            }
        });
        getContentPane().add(jB_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 100, 60));

        jB_samadengan.setText("=");
        jB_samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_samadenganActionPerformed(evt);
            }
        });
        getContentPane().add(jB_samadengan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 100, 60));

        jB_1.setText("1");
        jB_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_1ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 100, 60));

        jB_2.setText("2");
        jB_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_2ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 90, 60));

        jB_3.setText("3");
        jB_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_3ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 100, 60));

        jB_4.setText("4");
        jB_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_4ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 100, 60));

        jB_5.setText("5");
        jB_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_5ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 90, 60));

        jB_6.setText("6");
        jB_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_6ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 100, 60));

        jB_7.setText("7");
        jB_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_7ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 100, 60));

        jB_8.setText("8");
        jB_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_8ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 90, 60));

        jB_9.setText("9");
        jB_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_9ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 100, 60));

        jB_0.setText("0");
        jB_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_0ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 200, 60));

        jB_koma.setText(",");
        jB_koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_komaActionPerformed(evt);
            }
        });
        getContentPane().add(jB_koma, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 100, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jT_resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_resultActionPerformed
    
    }//GEN-LAST:event_jT_resultActionPerformed

    private void jB_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_2ActionPerformed
    angka += "2";
    jT_result.setText(angka);
    }//GEN-LAST:event_jB_2ActionPerformed

    private void jB_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_4ActionPerformed
    angka += "4";
    jT_result.setText(angka);
    }//GEN-LAST:event_jB_4ActionPerformed

    private void jB_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_3ActionPerformed
    angka += "3";
    jT_result.setText(angka);
    }//GEN-LAST:event_jB_3ActionPerformed

    private void jB_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_1ActionPerformed
    angka += "1";
    jT_result.setText(angka);
    }//GEN-LAST:event_jB_1ActionPerformed

    private void jB_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_tambahActionPerformed
    angka1 = Double.parseDouble(angka);
    jT_result.setText("+");
    angka = "";
    pilih = 1;
    
    }//GEN-LAST:event_jB_tambahActionPerformed

    private void jB_samadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_samadenganActionPerformed
    switch(pilih) {
        case 1:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 + angka2;
            angka = Double.toString(jumlah);
            jT_result.setText(angka);
            break;
        case 2:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 - angka2;
            angka = Double.toString(jumlah);
            jT_result.setText(angka);
            break;
        case 3:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 * angka2;
            angka = Double.toString(jumlah);
            jT_result.setText(angka);
            break;
        case 4:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 / angka2;
            angka = Double.toString(jumlah);
            jT_result.setText(angka);
            break;
        default:
            break;
    }
    }//GEN-LAST:event_jB_samadenganActionPerformed
   
    private void jB_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_5ActionPerformed
    angka += "5";
    jT_result.setText(angka);
    }//GEN-LAST:event_jB_5ActionPerformed

    private void jB_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_6ActionPerformed
    angka += "6";
    jT_result.setText(angka);
    }//GEN-LAST:event_jB_6ActionPerformed

    private void jB_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_7ActionPerformed
    angka += "7";
    jT_result.setText(angka);
    }//GEN-LAST:event_jB_7ActionPerformed

    private void jB_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_8ActionPerformed
    angka += "8";
    jT_result.setText(angka);
    }//GEN-LAST:event_jB_8ActionPerformed

    private void jB_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_9ActionPerformed
    angka += "9";
    jT_result.setText(angka);
    }//GEN-LAST:event_jB_9ActionPerformed

    private void jB_komaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_komaActionPerformed
    angka += ",";
    jT_result.setText(angka);
    }//GEN-LAST:event_jB_komaActionPerformed

    private void jB_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_0ActionPerformed
    angka += "0";
    jT_result.setText(angka);
    }//GEN-LAST:event_jB_0ActionPerformed

    private void jB_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ClearActionPerformed
    jT_result.setText("");
    angka1 = 0.0;
    angka2 = 0.0;
    jumlah = 0.0;
    angka = "";
    }//GEN-LAST:event_jB_ClearActionPerformed

    private void jB_bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_bagiActionPerformed
    angka1 = Double.parseDouble(angka);
    jT_result.setText("/");
    angka = "";
    pilih = 4;
    }//GEN-LAST:event_jB_bagiActionPerformed

    private void jB_kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_kurangActionPerformed
    angka1 = Double.parseDouble(angka);
    jT_result.setText("-");
    angka = "";
    pilih = 2;
    }//GEN-LAST:event_jB_kurangActionPerformed

    private void jB_kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_kaliActionPerformed
    angka1 = Double.parseDouble(angka);
    jT_result.setText("*");
    angka = "";
    pilih = 3;
    }//GEN-LAST:event_jB_kaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_0;
    private javax.swing.JButton jB_1;
    private javax.swing.JButton jB_2;
    private javax.swing.JButton jB_3;
    private javax.swing.JButton jB_4;
    private javax.swing.JButton jB_5;
    private javax.swing.JButton jB_6;
    private javax.swing.JButton jB_7;
    private javax.swing.JButton jB_8;
    private javax.swing.JButton jB_9;
    private javax.swing.JButton jB_Clear;
    private javax.swing.JButton jB_bagi;
    private javax.swing.JButton jB_kali;
    private javax.swing.JButton jB_koma;
    private javax.swing.JButton jB_kurang;
    private javax.swing.JButton jB_samadengan;
    private javax.swing.JButton jB_tambah;
    private javax.swing.JTextField jT_result;
    // End of variables declaration//GEN-END:variables
}
